FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade uv

COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock
COPY app /app/app
COPY alembic /app/alembic
COPY alembic.ini /app/alembic.ini

RUN uv sync --no-dev --locked

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="/app/.venv/bin:$PATH"

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
