FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade uv

COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock
COPY app /app/app
COPY consumer /app/consumer

RUN uv sync --system --no-dev --locked

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "consumer.main"]
